import torch

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

USTX_DIR = "3"
VOCAB_PATH = "phoneme_vocab_lstm.yaml"
BATCH_SIZE = 256
SEQUENCE_LEN =  5
MAX_PITCH_POINTS = 100

PHONEME_EMBEDDING_DIM = 128
NOTE_FEATURE_DIM = 6
ENCODER_HIDDEN_DIM = 128
ENCODER_NUM_LAYERS = 3
DECODER_HIDDEN_DIM = 128
DECODER_NUM_LAYERS = 3
DROPOUT = 0.2
ATTENTION_HEADS = 16

EPOCHS = 150
LEARNING_RATE = 0.001
PLOT_EVERY = 5
MODEL_SAVE_PATH = "autopitch_lstm_best.pth" 